version: '2'

services:
    memcached:
        image: memcached
        restart: always
    webapp:
        build:
            context: .
            dockerfile: ./Dockerfile-dev
        user: nobody
        restart: always
        depends_on:
            - memcached
        ports:
            - "8000:8000"